#!/bin/bash
CADMIUMROOT=$(dirname $(dirname $(realpath $0)))

set -e

[ -z "$TARGET" ] && source $CADMIUMROOT/config

source $CADMIUMROOT/flavor/$FLAV

mkdir -p $CADMIUMROOT/tmp
cd $CADMIUMROOT/tmp


#git clone https://gitlab.collabora.com/google/chromeos-kernel.git -b mt8195-tracking-master-rolling linux-$ARCH
#cd linux-$ARCH
#echo "Applying Cadmium Logo"
#patch -p1 --forward < $CADMIUMROOT/kernel/patches/common.add-custom-logo-and-show-it-regardless-of-loglevel.patch


cd $CADMIUMROOT/tmp/linux-$ARCH

if [ $KERNEL = libre ]; then
	# it looks better this way
	sed -i'' 's/cadmium/-cadmium/' .config
fi

#make nconfig # if you want to customize config just uncomment this

echo "Bulding $KERNEL kernel for $ARCH in $(pwd) with $THREADS threads using $CROSS_COMPILE"
time make -j"$THREADS"

# FIXME: broken on loongson2f
#make tarxz-pkg
